### ISSUE TITLE
Grafana crashes: /var/lib/grafana is not writable

### ISSUE THREAD

**Issue by Stefan-Code** [cfbarbero/tick-grafana-docker#1]
When running `docker-compose up` grafana crashes with:
```
grafana_1        | GF_PATHS_DATA='/var/lib/grafana' is not writable.
grafana_1        | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
grafana_1        | mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```

Pretty sure this is related to https://github.com/grafana/grafana-docker/issues/154

**Comment by Stefan-Code** [comment]
This can be solved by manually `chown`-ing the grafana directory on the host to `472:472`, but there's got to be a better way.

**Comment by raul1991** [comment]
Even doing a chown does not fix it. I have fsGroup: 472 runAsUser: 472 and the directories belong to 472:472

**Comment by brianfeucht** [comment]
@raul1991 newer versions of grafana are using user `104`  I had to `chown 104:104 /data/grafana` and it works with this in my docker compose:
```
  grafana:
    image: grafana/grafana:7.0.1
    volumes:
        - /data/grafana:/var/lib/grafana 
    ports:
        - "3000:3000"
    user: "104"
```

**Comment by raul1991** [comment]
@brianfeucht Thanks for.the update. Can you confirm if 472:472 works with version 6 of grafana.

**Comment by brianfeucht** [comment]
@raul1991 the change to `uid:104`  was made in `v5.1` - http://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v5-1-or-later

I did confirm that `chown 472:472 /data/grafana2` works with the following docker-compose config:
```
  grafana:
    image: grafana/grafana:7.0.1
    volumes:
        - /data/grafana2:/var/lib/grafana 
    ports:
        - "3000:3000"
    user: "472"
```

**Comment by juanmercadoit** [comment]
Hi all:

I had the same issue and solved with 2 steps:

1) Identified the OS user and id.
2) Change the docker compose.
3) Run docker-compos fine without errors !

### Example:

```grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    user: "1014"
```
The User id

```
drwxr-xr-x  4 grafana root 4096 Feb  5 16:45 data/
drwxr-xr-x  3 grafana root 4096 Feb  5 17:47 var/
```
**Working Fine !**

**Comment by IIIdefconIII** [comment]
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later

**Comment by devhero** [comment]
`user: "${UID}:${GID}"` solves the permission issue
`image: grafana/grafana:main` use the most recent

```
grafana:
    image: grafana/grafana:main
    volumes:
        - /data/grafana:/var/lib/grafana 
    ports:
        - "3000:3000"
    user: "${UID}:${GID}"
```
